test

diff --git a/.github/workflows/backend-pipeline.yml b/.github/workflows/backend-pipeline.yml
--- a/.github/workflows/backend-pipeline.yml
+++ b/.github/workflows/backend-pipeline.yml
@@ -7,17 +7,16 @@ on:
             - develop
             - uat
             - main
-
         paths:
             - 'apps/backend/**'
             - 'libs/shared/**'
 
 jobs:
-    backend:
-        name: Backend Build and Deploy
+    build:
+        name: Build Backend
         runs-on: ubuntu-latest
         steps:
-            - name: Checkout code
+            - name: Checkout Code
               uses: actions/checkout@v4
 
             - name: Set up Docker Buildx
@@ -29,48 +28,154 @@ jobs:
                   username: ${{ secrets.DOCKER_USERNAME }}
                   password: ${{ secrets.DOCKER_PASSWORD }}
 
-            # - name: Set environment for backend
-            #   id: set-env
-            #   run: |
-            #       if [[ $GITHUB_REF == refs/heads/develop ]]; then
-            #         echo "env=develop" >> $GITHUB_ENV
-            #         echo "docker_tag=develop" >> $GITHUB_ENV
-            #         echo "render_service_id=${{ secrets.RENDER_BACKEND_SERVICE_DEV }}" >> $GITHUB_ENV
-            #       elif [[ $GITHUB_REF == refs/heads/uat ]]; then
-            #         echo "env=uat" >> $GITHUB_ENV
-            #         echo "docker_tag=uat" >> $GITHUB_ENV
-            #         echo "render_service_id=${{ secrets.RENDER_BACKEND_SERVICE_UAT }}" >> $GITHUB_ENV
-            #       elif [[ $GITHUB_REF == refs/heads/main ]]; then
-            #         echo "env=prod" >> $GITHUB_ENV
-            #         echo "docker_tag=prod" >> $GITHUB_ENV
-            #         echo "render_service_id=${{ secrets.RENDER_BACKEND_SERVICE_PROD }}" >> $GITHUB_ENV
-            #       fi
+            - name: Set Environment Variables
+              run: |
+                  case $GITHUB_REF in
+                    refs/heads/develop)
+                      echo "PORT_BACKEND=8000" >> $GITHUB_ENV
+                      echo "DOCKER_TAG=develop" >> $GITHUB_ENV
+                      ;;
+                    refs/heads/uat)
+                      echo "PORT_BACKEND=8000" >> $GITHUB_ENV
+                       echo "DOCKER_TAG=uat" >> $GITHUB_ENV
+                      ;;
+                    refs/heads/main)
+                      echo "PORT_BACKEND=8000" >> $GITHUB_ENV
+                      echo "DOCKER_TAG=prod" >> $GITHUB_ENV
+                      ;;
+                  esac
 
-            # - name: Build Backend Docker Image
-            #   run: |
-            #       docker build \
-            #         --build-arg APP_ENV=${{ secrets.APP_ENV }} \
-            #         --build-arg PORT_BACKEND=${{ secrets.PORT_BACKEND }} \
-            #         --build-arg PORT_FRONTEND=${{ secrets.PORT_FRONTEND }} \
-            #         --build-arg ROUTE_PREFIX=${{ secrets.ROUTE_PREFIX }} \
-            #         --build-arg KEY_VAULT_URI=${{ secrets.KEY_VAULT_URI }} \
-            #         --build-arg TENANT_ID=${{ secrets.TENANT_ID }} \
-            #         --build-arg CLIENT_ID=${{ secrets.CLIENT_ID }} \
-            #         --build-arg CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} \
-            #         -t ${{ secrets.DOCKER_USERNAME }}/backend:${{ env.docker_tag }} \
-            #         -f devops/backend/Dockerfile .
+            - name: Backup existing image if exists
+              run: |
+                  IMAGE_EXISTS=$(docker manifest inspect ${{ secrets.DOCKER_USERNAME }}/backend:${{ env.DOCKER_TAG }} > /dev/null 2>&1 && echo "YES" || echo "NO")
+                  if [ "$IMAGE_EXISTS" = "YES" ]; then
+                    echo "Backup existing image..."
 
-            # - name: Push Backend Image to DockerHub
-            #   run: |
-            #       docker push ${{ secrets.DOCKER_USERNAME }}/backend:${{ env.docker_tag }}
+                    docker pull ${{ secrets.DOCKER_USERNAME }}/backend:${{ env.DOCKER_TAG }}
+                    docker tag ${{ secrets.DOCKER_USERNAME }}/backend:${{ env.DOCKER_TAG }} ${{ secrets.DOCKER_USERNAME }}/backend:${{ env.DOCKER_TAG }}_backup
+                    docker push ${{ secrets.DOCKER_USERNAME }}/backend:${{ env.DOCKER_TAG }}_backup
+                  else
+                    echo "No existing image to backup."
+                  fi
 
-            # - name: Deploy Backend to Render
-            #   run: |
-            #       curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
-            #       -H "Content-Type: application/json" \
-            #       --data '{
-            #         "serviceId": "${{ env.render_service_id }}",
-            #         "image": "${{ secrets.DOCKER_USERNAME }}/backend:${{ env.docker_tag }}",
-            #         "clearCache": true
-            #       }' \
-            #       ${{ secrets.RENDER_API_URL }}/v1/services/${{ env.render_service_id }}/deploys
+            - name: Build and Push Backend Docker Image
+              uses: docker/build-push-action@v6
+              with:
+                  context: .
+                  file: devops/backend/Dockerfile
+                  push: true
+                  tags: ${{ secrets.DOCKER_USERNAME }}/backend:${{ env.DOCKER_TAG }}
+                  build-args: |
+                      PORT_BACKEND=${{ env.PORT_BACKEND }}
+
+    # deploy:
+    #     name: Deploy Backend
+    #     runs-on: ubuntu-latest
+    #     needs: build
+    #     steps:
+    #         - name: Set Environment Variables
+    #           run: |
+    #               case $GITHUB_REF in
+    #                 refs/heads/develop)
+    #                   echo "APP_ENV=DEV" >> $GITHUB_ENV
+    #                   echo "PORT_BACKEND=8000" >> $GITHUB_ENV
+    #                   echo "PORT_FRONTEND=80" >> $GITHUB_ENV
+    #                   echo "DOCKER_TAG=develop" >> $GITHUB_ENV
+    #                   echo "SERVER_HOST=${{ secrets.DEV_SERVER_HOST }}" >> $GITHUB_ENV
+    #                   echo "SERVER_PASS_PHRASE=${{ secrets.DEV_SERVER_PASS_PHRASE }}" >> $GITHUB_ENV
+    #                   echo "SERVER_PRIVATE_SSH_KEY<<EOF" >> $GITHUB_ENV
+    #                   echo "${{ secrets.DEV_SERVER_PRIVATE_SSH_KEY }}" >> $GITHUB_ENV
+    #                   echo "EOF" >> $GITHUB_ENV
+    #                   echo "SERVER_USER=${{ secrets.DEV_SERVER_USER }}" >> $GITHUB_ENV
+    #                   ;;
+    #                 refs/heads/uat)
+    #                   echo "APP_ENV=UAT" >> $GITHUB_ENV
+    #                   echo "PORT_BACKEND=8000" >> $GITHUB_ENV
+    #                   echo "PORT_FRONTEND=80" >> $GITHUB_ENV
+    #                   echo "DOCKER_TAG=uat" >> $GITHUB_ENV
+    #                   echo "SERVER_HOST=${{ secrets.UAT_SERVER_HOST }}" >> $GITHUB_ENV
+    #                   echo "SERVER_PASS_PHRASE=${{ secrets.UAT_SERVER_PASS_PHRASE }}" >> $GITHUB_ENV
+    #                   echo "SERVER_PRIVATE_SSH_KEY<<EOF" >> $GITHUB_ENV
+    #                   echo "${{ secrets.UAT_SERVER_PRIVATE_SSH_KEY }}" >> $GITHUB_ENV
+    #                   echo "EOF" >> $GITHUB_ENV
+    #                   echo "SERVER_USER=${{ secrets.UAT_SERVER_USER }}" >> $GITHUB_ENV
+    #                   ;;
+    #                 refs/heads/main)
+    #                   echo "APP_ENV=PROD" >> $GITHUB_ENV
+    #                   echo "PORT_BACKEND=8000" >> $GITHUB_ENV
+    #                   echo "PORT_FRONTEND=80" >> $GITHUB_ENV
+    #                   echo "DOCKER_TAG=prod" >> $GITHUB_ENV
+    #                   echo "SERVER_HOST=${{ secrets.PROD_SERVER_HOST }}" >> $GITHUB_ENV
+    #                   echo "SERVER_PASS_PHRASE=${{ secrets.PROD_SERVER_PASS_PHRASE }}" >> $GITHUB_ENV
+    #                   echo "SERVER_PRIVATE_SSH_KEY<<EOF" >> $GITHUB_ENV
+    #                   echo "${{ secrets.PROD_SERVER_PRIVATE_SSH_KEY }}" >> $GITHUB_ENV
+    #                   echo "EOF" >> $GITHUB_ENV
+    #                   echo "SERVER_USER=${{ secrets.PROD_SERVER_USER }}" >> $GITHUB_ENV
+    #                   ;;
+    #               esac
+
+    #         - name: Deploy to Digital Ocean Droplet via SSH
+    #           uses: appleboy/ssh-action@v1.0.3
+    #           with:
+    #               host: ${{ env.SERVER_HOST }}
+    #               username: ${{ env.SERVER_USER }}
+    #               key: ${{ env.SERVER_PRIVATE_SSH_KEY }}
+    #               passphrase: ${{ env.SERVER_PASS_PHRASE }}
+    #               script: |
+    #                   # Check if Docker is installed
+    #                   if ! command -v docker &> /dev/null; then
+    #                       echo "Docker not found, installing..."
+
+    #                       # Install Docker
+    #                       curl -fsSL https://get.docker.com -o get-docker.sh
+    #                       sh get-docker.sh
+    #                   else
+    #                       echo "Docker is already installed."
+    #                   fi
+
+    #                   # Pull the latest image
+    #                   docker pull ${{ secrets.DOCKER_USERNAME }}/backend:${{ env.DOCKER_TAG }}
+
+    #                   # Check if the container is running
+    #                   if [ "$(docker ps -q -f name=backend)" ]; then
+    #                       # Stop and remove the old container if it exists
+    #                       docker stop backend
+    #                       docker rm backend
+    #                   fi
+
+    #                   # Run the new container
+    #                   docker run -d \
+    #                     --restart always \
+    #                     --name backend \
+    #                     -p ${{ env.PORT_BACKEND }}:${{ env.PORT_BACKEND }} \
+    #                     -e APP_ENV=${{ env.APP_ENV }} \
+    #                     -e PORT_BACKEND=${{ env.PORT_BACKEND }} \
+    #                     ${{ secrets.DOCKER_USERNAME }}/backend:${{ env.DOCKER_TAG }}
+
+    #                   # Check if the new container started successfully
+    #                   if [ "$(docker ps -q -f name=backend)" ]; then
+    #                       echo "Backend container started successfully."
+    #                   else
+    #                       echo "New backend container failed to start. Rolling back to backup..."
+
+    #                       # Stop and remove failed container (if it exists)
+    #                       docker stop backend || true
+    #                       docker rm backend || true
+
+    #                       # Pull the latest image
+    #                       docker pull ${{ secrets.DOCKER_USERNAME }}/backend:${{ env.DOCKER_TAG }}_backup
+
+    #                       # Start the previous backed-up container
+    #                       docker run -d \
+    #                         --restart always \
+    #                         --name backend \
+    #                         -p ${{ env.PORT_BACKEND }}:${{ env.PORT_BACKEND }} \
+    #                         -e APP_ENV=${{ env.APP_ENV }} \
+    #                         -e PORT_BACKEND=${{ env.PORT_BACKEND }} \
+    #                         ${{ secrets.DOCKER_USERNAME }}/backend:${{ env.DOCKER_TAG }}_backup
+
+    #                       echo "Rolled back to the previous backend container."
+    #                   fi
+
+    #                   # Remove old backend images (dangling images)
+    #                   docker images --filter "dangling=true" --format "{{.ID}}" | xargs -r docker rmi || true
